In [1]:
import pandas as pd
df = pd.read_csv("earthquakedata.csv")
df.head()

,Unnamed: 0,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,0,2000-01-01T01:19:26.990Z,41.9270,20.543,10.0,4.5,mb,NaN,NaN,NaN,...,2014-11-07T01:09:14.397Z,"14 km SW of Dragash, Kosovo",earthquake,NaN,NaN,NaN,18.0,reviewed,us,us
1,1,2000-01-01T02:10:15.590Z,41.9150,20.534,6.2,2.9,md,NaN,NaN,NaN,...,2014-11-07T01:09:14.652Z,"15 km SW of Dragash, Kosovo",earthquake,NaN,NaN,NaN,NaN,reviewed,pdg,pdg
2,2,2000-01-01T02:12:13.450Z,-11.3480,164.568,33.0,4.3,mb,NaN,NaN,NaN,...,2014-11-07T01:09:14.702Z,"150 km WSW of Lata, Solomon Islands",earthquake,NaN,NaN,NaN,2.0,reviewed,us,us
3,3,2000-01-01T03:20:57.300Z,48.1190,-2.959,3.0,2.7,ml,NaN,NaN,NaN,...,2014-11-07T01:09:14.711Z,"2 km ESE of Neulliac, France",earthquake,NaN,NaN,NaN,NaN,reviewed,ldg,ldg
4,4,2000-01-01T03:24:23.217Z,62.7531,-150.301,93.3,2.5,ml,NaN,NaN,NaN,...,2020-02-20T20:06:40.502Z,"35 km NNW of Chase, Alaska",earthquake,NaN,3.2,NaN,NaN,reviewed,ak,ak

In [2]:
import csv
from plotly.graph_objs import Scattergeo, Layout
from plotly import offline

In [3]:
filename = 'earthquakedata.csv'
with open(filename, encoding='utf8') as f:
  reader = csv.reader(f)
  header_row = next(reader)

In [4]:

# Accessing the csv file
filename = 'earthquakedata.csv'
with open(filename, encoding='utf8') as f:
  reader = csv.reader(f)
  header_row = next(reader)

  ## Printing each column name and its index number
  # for index, column_name in enumerate(header_row):
  #    print(index, column_name)
  ## Notes: 1-time, 2-latitude, 3-longitude, 5-mag, 14-place

  # Getting the necessary lists of values
  mags, lats, lons, hover_texts = [], [], [], []
  for row in reader:
    mag_min = 5.5
    if float(row[5]) >= mag_min:
        try:
            mag = float(row[5])
            lat = float(row[2])
            lon = float(row[3])
            hover_this = f"Mag: {mag}/ {row[14]}/ Date (Y-m-d): {row[1][:10]}"
        except ValueError:
            print(f"Missing data on {row[1]}.")
        else:
            mags.append(mag)
            lats.append(lat)
            lons.append(lon)
            hover_texts.append(hover_this)

# Customizing the map to make it more accessible to see
data = [{
 'type':'scattergeo',
 'lon': lons,
 'lat': lats,
 'text': hover_texts,
 'marker':{
  'size': [4*mag if mag>=7 else 2*mag for mag in mags],
  'color': mags,
  'colorscale': 'rdylgn',
  'reversescale': True,
  'colorbar': {'title':'Magnitude'},
 },
}]

my_title = dict(text=f"Earthquakes with Magnitude {mag_min} and Above, Since January 2000<br />Total Number of Events = {len(mags)} (Data from USGS)", font=dict(size=30))
my_layout = Layout(title=my_title, title_x=0.5)

# Producing the Map of Earthquakes Distribution
fig = {'data': data, 'layout': my_layout}
offline.plot(fig, filename='Global_EarthQuakes_Since_2000.html')

'Global_EarthQuakes_Since_2000.html'